my_file = open("protein.txt")
content = my_file.read()
my_file.close()

A_count = content.count("A")
C_count = content.count("C")
D_count = content.count("D")
E_count = content.count("E")
F_count = content.count("F")
G_count = content.count("G")
H_count = content.count("H")
I_count = content.count("I")
K_count = content.count("K")
L_count = content.count("L")
M_count = content.count("M")
N_count = content.count("N")
P_count = content.count("P")
Q_count = content.count("Q")
R_count = content.count("R")
S_count = content.count("S")
T_count = content.count("T")
V_count = content.count("V")
W_count = content.count("W")
Y_count = content.count("Y")


print("A: " + str(A_count))
print("C: " + str(C_count))
print("D: " + str(D_count))
print("E: " + str(E_count))
print("F: " + str(F_count))
print("G: " + str(G_count))
print("H: " + str(H_count))
print("I: " + str(I_count))
print("K: " + str(K_count))
print("L: " + str(L_count))
print("M: " + str(M_count))
print("N: " + str(N_count))
print("P: " + str(P_count))
print("Q: " + str(Q_count))
print("R: " + str(R_count))
print("S: " + str(S_count))
print("T: " + str(T_count))
print("V: " + str(V_count))
print("W: " + str(W_count))
print("Y: " + str(Y_count))
